import { Layout } from "@/components/layout";
import { motion } from "framer-motion";
import { AlertTriangle } from "lucide-react";

const LAST_UPDATED = "March 26, 2026";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-xl font-bold font-display mb-4 text-foreground">{title}</h2>
      <div className="space-y-3 text-muted-foreground leading-relaxed text-sm">{children}</div>
    </section>
  );
}

export default function Disclaimer() {
  return (
    <Layout>
      <div className="bg-background">
        {/* Hero */}
        <section className="py-16 bg-amber-50 dark:bg-amber-950/20 border-b border-amber-100 dark:border-amber-900/30">
          <div className="container mx-auto px-4 max-w-3xl text-center">
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
              <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-400 font-semibold text-sm mb-5 border border-amber-200 dark:border-amber-800">
                <AlertTriangle className="w-4 h-4" />
                <span>Important information</span>
              </div>
              <h1 className="text-4xl md:text-5xl font-display font-bold tracking-tight mb-4">Disclaimer</h1>
              <p className="text-muted-foreground text-sm">Last updated: {LAST_UPDATED}</p>
            </motion.div>
          </div>
        </section>

        {/* Content */}
        <div className="container mx-auto px-4 max-w-3xl py-16">
          <div className="bg-card rounded-2xl border border-border/50 p-8 md:p-12">

            <p className="text-muted-foreground text-sm leading-relaxed mb-8">
              This Disclaimer applies to creatorsToolHub ("we," "us," or "our"), accessible at <strong>creatorstoolhub.com</strong>. By using our platform and its free creator tools — including YouTube automation tools, TikTok content generators, Instagram tools, and AI prompt generators — you accept the terms of this Disclaimer in full. Please read it carefully before using our services.
            </p>

            <Section title="1. AI-Generated Content">
              <p>creatorsToolHub uses artificial intelligence technology to generate content such as YouTube video scripts, viral titles, TikTok video ideas, Instagram captions, blog hooks, hashtags, prompts, and other creator content. While we have designed our tools to produce helpful and high-quality outputs, you should be aware of the following:</p>
              <ul className="list-disc list-inside mt-3 space-y-1 ml-2">
                <li>AI-generated content is produced algorithmically and may contain factual inaccuracies, errors, outdated information, or inconsistencies</li>
                <li>Outputs may not always be grammatically perfect, culturally appropriate for every audience, or aligned with platform-specific best practices at all times</li>
                <li>Generated content should always be reviewed, fact-checked, and edited by the user before publication or professional use</li>
                <li>creatorsToolHub does not review every output generated and cannot guarantee the accuracy, quality, or completeness of any AI-generated content</li>
              </ul>
              <p className="mt-3"><strong>You are solely responsible</strong> for any content you publish that is based on, or derived from, outputs generated by creatorsToolHub's free creator tools.</p>
            </Section>

            <Section title="2. No Guarantee of Results">
              <p>creatorsToolHub and its free AI tools for content creators are designed to help creators work faster and produce better content. However, we make no warranties or guarantees — express or implied — regarding specific outcomes. This includes but is not limited to:</p>
              <ul className="list-disc list-inside mt-3 space-y-1 ml-2">
                <li><strong>Viral performance:</strong> Using our viral title generator, TikTok content generator, or any other tool does not guarantee that your content will go viral, receive a specific number of views, or trend on any platform</li>
                <li><strong>Revenue or income:</strong> Our YouTube Money Calculator and similar tools provide estimates based on industry averages and publicly available CPM data. These are illustrative estimates only — actual earnings vary significantly based on many factors outside our control</li>
                <li><strong>Algorithm performance:</strong> YouTube, TikTok, and Instagram algorithms change frequently. Content strategies that work today may not be as effective in future</li>
                <li><strong>Growth outcomes:</strong> Follower growth, subscriber increases, and engagement improvements depend on many factors including content quality, posting frequency, audience targeting, and platform changes — none of which creatorsToolHub controls</li>
              </ul>
            </Section>

            <Section title="3. Not Professional Advice">
              <p>The content generated by creatorsToolHub's free creator tools — including scripts, captions, content plans, prompts, blog post ideas, and other outputs — is for informational and creative assistance purposes only. It does not constitute:</p>
              <ul className="list-disc list-inside mt-3 space-y-1 ml-2">
                <li>Legal advice</li>
                <li>Financial or investment advice</li>
                <li>Medical or health advice</li>
                <li>Business or marketing consulting</li>
                <li>Professional creative services</li>
              </ul>
              <p className="mt-3">If you require professional advice in any of these areas, please consult a qualified professional.</p>
            </Section>

            <Section title="4. Third-Party Platforms">
              <p>creatorsToolHub provides tools designed to create content for third-party platforms including YouTube, TikTok, Instagram, and others. Our platform is independent and not affiliated with, endorsed by, or sponsored by Google, YouTube, TikTok, Meta (Instagram), Anthropic (Claude), OpenAI (ChatGPT), Midjourney, or any other third-party platform or company referenced in our tools or content.</p>
              <p className="mt-3">Third-party platform terms of service and community guidelines apply to content you publish using outputs from our tools. You are responsible for ensuring your content complies with all applicable platform policies.</p>
            </Section>

            <Section title="5. External Links">
              <p>creatorsToolHub may contain links to external websites for reference or informational purposes. We do not control or take responsibility for the content, accuracy, or privacy practices of any linked external websites. The inclusion of any link does not imply our endorsement of the linked site.</p>
            </Section>

            <Section title="6. Availability of Service">
              <p>We strive to keep creatorsToolHub available at all times, but we cannot guarantee uninterrupted access. The platform may be temporarily unavailable due to maintenance, technical issues, server outages, or events outside our control. We are not liable for any disruption or loss caused by unavailability of our free creator tools.</p>
            </Section>

            <Section title="7. Changes to This Disclaimer">
              <p>We may update this Disclaimer from time to time. Any changes will be reflected by updating the "Last updated" date above. Your continued use of creatorsToolHub after updates constitutes your acceptance of the revised Disclaimer.</p>
            </Section>

            <Section title="8. Contact">
              <p>If you have questions about this Disclaimer, please contact us:</p>
              <div className="mt-3 p-4 rounded-xl bg-muted/40 border border-border/40">
                <p><strong>creatorsToolHub</strong></p>
                <p>Email: <a href="mailto:hello@creatorstoolhub.com" className="text-primary hover:underline">hello@creatorstoolhub.com</a></p>
                <p>Website: <a href="https://creatorstoolhub.com" className="text-primary hover:underline">creatorstoolhub.com</a></p>
              </div>
            </Section>

          </div>
        </div>
      </div>
    </Layout>
  );
}
