import { Layout } from "@/components/layout";
import { motion } from "framer-motion";
import { FileText } from "lucide-react";

const LAST_UPDATED = "March 26, 2026";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-xl font-bold font-display mb-4 text-foreground">{title}</h2>
      <div className="space-y-3 text-muted-foreground leading-relaxed text-sm">{children}</div>
    </section>
  );
}

export default function Terms() {
  return (
    <Layout>
      <div className="bg-background">
        {/* Hero */}
        <section className="py-16 bg-primary/5 border-b border-border">
          <div className="container mx-auto px-4 max-w-3xl text-center">
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
              <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 text-primary font-semibold text-sm mb-5 border border-primary/20">
                <FileText className="w-4 h-4" />
                <span>Legal</span>
              </div>
              <h1 className="text-4xl md:text-5xl font-display font-bold tracking-tight mb-4">Terms & Conditions</h1>
              <p className="text-muted-foreground text-sm">Last updated: {LAST_UPDATED}</p>
            </motion.div>
          </div>
        </section>

        {/* Content */}
        <div className="container mx-auto px-4 max-w-3xl py-16">
          <div className="bg-card rounded-2xl border border-border/50 p-8 md:p-12">

            <p className="text-muted-foreground text-sm leading-relaxed mb-8">
              These Terms and Conditions ("Terms") govern your access to and use of creatorsToolHub ("we," "us," or "our"), accessible at <strong>creatorstoolhub.com</strong>. By accessing or using our platform — which provides free AI-powered tools for content creators, including YouTube automation tools, TikTok content generators, and Instagram tools — you agree to be bound by these Terms. If you do not agree, please discontinue use of our platform.
            </p>

            <Section title="1. Acceptance of Terms">
              <p>By accessing creatorsToolHub, you confirm that you are at least 13 years of age (or 16 in some jurisdictions), that you have the legal capacity to enter into these Terms, and that you will comply with all applicable laws and regulations. If you are using the platform on behalf of an organisation, you represent that you have authority to bind that organisation to these Terms.</p>
            </Section>

            <Section title="2. Description of Service">
              <p>creatorsToolHub provides a collection of free, AI-powered content creation tools designed for YouTube creators, TikTok creators, Instagram creators, and other online content producers. Our tools include but are not limited to: YouTube script generators, viral title generators, TikTok content generators, Instagram caption generators, AI prompt generators, Midjourney prompt generators, hashtag generators, hook generators, and engagement calculators.</p>
              <p>All tools on creatorsToolHub are free to use. We reserve the right to modify, suspend, or discontinue any tool or feature at any time without prior notice.</p>
            </Section>

            <Section title="3. AI-Generated Content Disclaimer">
              <p>Our tools use artificial intelligence to generate content, including scripts, titles, captions, prompts, and ideas. You acknowledge and agree that:</p>
              <ul className="list-disc list-inside mt-2 space-y-1 ml-2">
                <li>AI-generated content is produced algorithmically and may contain inaccuracies, errors, or outdated information</li>
                <li>Output should be reviewed and edited before publication or professional use</li>
                <li>We do not guarantee that any AI-generated content will achieve specific outcomes, including viral performance, increased views, or revenue growth</li>
                <li>You are solely responsible for reviewing, editing, and determining the suitability of any content generated by our tools before using it</li>
                <li>AI-generated content does not constitute professional, legal, medical, financial, or any other form of expert advice</li>
              </ul>
            </Section>

            <Section title="4. Intellectual Property">
              <p><strong>Our Content:</strong> The creatorsToolHub platform, including its design, code, branding, logos, tool interfaces, and blog content, is owned by creatorsToolHub and protected by applicable intellectual property laws. You may not copy, reproduce, modify, or distribute our platform content without express written permission.</p>
              <p className="mt-3"><strong>Your Content & Tool Outputs:</strong> Any content you generate using our free creator tools belongs to you. We do not claim ownership over outputs generated by our tools. However, by using our tools you grant us a non-exclusive, royalty-free licence to use anonymised, aggregated usage data to improve our platform and tools.</p>
              <p className="mt-3"><strong>Third-Party Content:</strong> You are responsible for ensuring that any inputs you provide to our tools (e.g. brand names, song lyrics, images) do not infringe third-party intellectual property rights.</p>
            </Section>

            <Section title="5. Acceptable Use Policy">
              <p>You agree to use creatorsToolHub only for lawful purposes. You must not use our platform to:</p>
              <ul className="list-disc list-inside mt-2 space-y-1 ml-2">
                <li>Generate content that is defamatory, abusive, harassing, threatening, or hateful</li>
                <li>Create spam, phishing content, or deceptive material</li>
                <li>Generate content that infringes any person's intellectual property rights</li>
                <li>Violate the terms of service of any platform (YouTube, TikTok, Instagram, etc.) where you publish generated content</li>
                <li>Attempt to reverse engineer, scrape, or exploit the technical infrastructure of our platform</li>
                <li>Use automated bots or scripts to make excessive requests to our tools</li>
                <li>Generate, distribute, or promote illegal content of any kind</li>
                <li>Impersonate any person, business, or organisation</li>
              </ul>
              <p className="mt-3">We reserve the right to restrict or terminate access to creatorsToolHub for any user found to be in violation of this Acceptable Use Policy.</p>
            </Section>

            <Section title="6. Advertising">
              <p>creatorsToolHub displays advertisements through Google AdSense to fund the platform and keep all tools free for creators. By using our platform, you acknowledge and consent to the display of contextual advertising. You agree not to click on advertisements artificially or manipulate advertising metrics in any way.</p>
            </Section>

            <Section title="7. Third-Party Links & Services">
              <p>Our platform may contain links to third-party websites or services (for example, links to YouTube, TikTok, or AI tools like ChatGPT and Midjourney). These links are provided for your convenience only. creatorsToolHub does not control and is not responsible for the content, privacy practices, or terms of any third-party website. Accessing third-party sites is at your own risk.</p>
            </Section>

            <Section title="8. Limitation of Liability">
              <p>To the fullest extent permitted by applicable law, creatorsToolHub and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from:</p>
              <ul className="list-disc list-inside mt-2 space-y-1 ml-2">
                <li>Your use of or inability to use our free creator tools</li>
                <li>Any errors, inaccuracies, or omissions in AI-generated content</li>
                <li>Any content you publish based on outputs from our tools</li>
                <li>Interruptions, outages, or changes to our platform</li>
                <li>Unauthorised access to or alteration of your data</li>
              </ul>
              <p className="mt-3">creatorsToolHub is provided on an "as is" and "as available" basis without warranties of any kind, express or implied, including warranties of merchantability, fitness for a particular purpose, or non-infringement.</p>
            </Section>

            <Section title="9. Indemnification">
              <p>You agree to indemnify, defend, and hold harmless creatorsToolHub and its operators from any claims, liabilities, damages, losses, or expenses (including legal fees) arising from your use of our platform, your violation of these Terms, or any content you generate, publish, or distribute using our tools.</p>
            </Section>

            <Section title="10. Changes to the Service and Terms">
              <p>We reserve the right to modify these Terms at any time. When we do, we will update the "Last updated" date. Your continued use of creatorsToolHub after any changes constitutes your acceptance of the updated Terms. We reserve the right to add, modify, or remove tools and features from the platform without notice.</p>
            </Section>

            <Section title="11. Governing Law">
              <p>These Terms are governed by and construed in accordance with applicable law. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the courts of the applicable territory. If any provision of these Terms is found to be unenforceable, the remaining provisions shall remain in full force and effect.</p>
            </Section>

            <Section title="12. Contact">
              <p>If you have any questions about these Terms and Conditions, please contact us:</p>
              <div className="mt-3 p-4 rounded-xl bg-muted/40 border border-border/40">
                <p><strong>creatorsToolHub</strong></p>
                <p>Email: <a href="mailto:hello@creatorstoolhub.com" className="text-primary hover:underline">hello@creatorstoolhub.com</a></p>
                <p>Website: <a href="https://creatorstoolhub.com" className="text-primary hover:underline">creatorstoolhub.com</a></p>
              </div>
            </Section>

          </div>
        </div>
      </div>
    </Layout>
  );
}
