import { useState, useRef, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card } from "@/components/ui/card";
import { useToast } from "@/hooks/use-toast";
import { useAiTool } from "@/hooks/use-ai-tool";
import {
  Sparkles, Copy, Check, Loader2, Film,
  ChevronDown, ListChecks, Shield, ArrowUpRight, Zap, TrendingUp, Lightbulb,
} from "lucide-react";
import { Link } from "wouter";

// ─── FAQ ──────────────────────────────────────────────────────────────────────

const FAQ_ITEMS = [
  {
    q: "What makes a good Instagram Reel idea?",
    a: "A good Instagram Reel idea answers four questions simultaneously: What exactly is the topic? (Not 'fitness tips' — '3 reasons your push-up form is preventing chest muscle growth.') What's the angle? (Not 'educational' — 'mistake callout that challenges what people have been told.') What's the hook? (Not 'start strong' — the exact first sentence under 12 words that creates curiosity or tension.) How do I film it? (The specific format — Talking Head, Tutorial, B-Roll, POV — not just 'on camera.') An idea that answers all four is filmable immediately. An idea that answers fewer than four is still a category, not a concept. Every idea this generator produces includes all four elements plus a specific filming tip, so you can move from reading to filming with no additional planning required.",
  },
  {
    q: "What are the best Instagram Reel formats in 2026?",
    a: "The nine highest-performing Reel formats are: (1) Talking Head — direct-to-camera; best for opinion content, personal experience, and educational breakdowns. Highest authority-building format. (2) B-Roll with Text Overlay — best for aspirational content like travel, morning routines, and lifestyle. (3) POV/Skit — highest comment rate because instant self-identification triggers emotional response. (4) Before & After — most reliably viral in transformation niches because visual contrast is processed instantly. (5) Tutorial/Demo — highest save rate because viewers want to reference the steps. (6) Storytime — creates the strongest viewer-creator bond; algorithm increasingly rewards authentic narratives. (7) Myth-Busting — high share rate because it creates a 'I need to tell people' social impulse. (8) Mistake Callout — high share rate for the same reason. (9) List/Tips — consistent performer because viewers know exactly what they'll get and completion motivation is high. The generator distributes ideas across all nine formats with no two consecutive ideas sharing the same format.",
  },
  {
    q: "How do I write a scroll-stopping hook for a Reel?",
    a: "A strong Reel hook must create one of three responses within the first two seconds: curiosity ('what happens next?'), tension ('I recognize that problem — is that me?'), or surprise ('I didn't know that — keep talking'). The most reliable hook structures are: (1) Mistake Callout — 'The [topic] mistake I see every [audience]…' (2) Contrarian — 'Stop [common advice]. Here's what actually works.' (3) Curiosity Gap — 'I spent [time/money] on [thing] so you don't have to.' (4) Number Promise — '3 things nobody tells you about [topic].' (5) POV — 'POV: You just realized [relatable moment].' Every hook generated by this tool is under 12 words — the maximum that can be processed in a 2-second scroll-stop window — and is tone-adjusted to Bold, Relatable, Inspirational, Funny, or Controversial delivery based on your settings.",
  },
  {
    q: "How many Reels should I post per week on Instagram?",
    a: "For accounts in growth mode (under 10K followers), posting 4–5 Reels per week is the most effective strategy for accelerating algorithmic discovery. Each Reel is an independent distribution event — a Reel you post on Tuesday gets pushed to a new audience segment that has no relationship to Monday's Reel, so volume directly compounds your reach. For accounts in the 10K–100K range focused on deepening audience relationships, 3–4 Reels per week balanced with Stories and carousels tends to perform better than Reels-only volume. For large accounts (100K+), 2–3 high-production Reels per week typically outperform higher-frequency lower-quality content. Regardless of your size, consistency beats peak volume — posting 3 Reels every week for 12 weeks outperforms posting 10 Reels in one week and then going quiet.",
  },
  {
    q: "What topics get the most views on Instagram Reels?",
    a: "The topics that consistently generate the highest Reel views fall into four categories: (1) Transformation content — before-and-after results in fitness, home improvement, financial progress, and skill development generate high shares and saves. (2) Mistake callouts — content that tells people they're doing something wrong in their own niche drives high engagement because it triggers defensive reading and social sharing. (3) Controversial or contrarian opinions — content that challenges mainstream advice in any niche generates comment debate and algorithmic amplification. (4) Hyper-specific tutorials — the more specific the tutorial, the higher the save rate, and save rate is Instagram's strongest Explore placement signal. 'How to do a handstand' performs worse than 'How to do a handstand against the wall if you're scared of falling.' Specificity is the single most underutilized lever for Reel performance.",
  },
  {
    q: "How do I film Instagram Reels with just my phone?",
    a: "A phone is sufficient for top-performing Reels — most of Instagram's highest-reach creator content is filmed on phones, not cameras. The key variables are lighting, stability, and audio. For lighting: natural light from a window (positioned in front of you, not behind) is free and flattering; a ring light is a worthwhile upgrade for talking-head Reels filmed indoors. For stability: prop your phone against a stack of books, use a $15 phone tripod, or invest in a phone gimbal for B-Roll movement. For audio: for talking-head Reels, a clip-on Lavalier microphone (under $30) eliminates background noise and dramatically improves perceived production quality; for B-Roll Reels, Instagram's built-in trending audio overlay is more important than your recording microphone. Vertical format (9:16 ratio, 1080×1920px) is the native Reels format and essential for full-screen display across all surfaces.",
  },
  {
    q: "What is the ideal Instagram Reel length in 2026?",
    a: "Instagram Reels can be up to 90 seconds long, but the algorithm rewards completion rate — the percentage of viewers who watch your Reel to the end. This means the optimal length is the shortest duration that fully delivers your idea. For hook-first entertaining content (POV, Storytime, Skit), 15–30 seconds maximises completion rate. For educational Reels (Tutorial, List, Myth-Busting), 30–60 seconds gives enough time to deliver the value while keeping the completion rate above the algorithmic threshold. For longer Storytime or before-and-after content that genuinely requires it, up to 90 seconds is acceptable if every second moves the narrative forward. The biggest mistake creators make is padding shorter ideas to feel more 'substantial' — a 45-second Reel with 20 seconds of filler performs worse algorithmically than a tight 25-second Reel with 100% completion.",
  },
  {
    q: "What is the difference between a viral Reel and a good Reel?",
    a: "A viral Reel maximises reach — it gets seen by as many people as possible in a short window. A good Reel maximises the right engagement for your specific goal. These are not always the same thing. A POV skit that gets 2 million views can bring in 10,000 followers who followed for entertainment and immediately unfollow when you post a product pitch. A Mistake Callout Reel that gets 50,000 views in your niche can bring in 3,000 highly engaged followers who are actively interested in your topic and buy from you. Virality without targeting is vanity — it feels good but rarely builds a monetisable audience. Use Goal selection in this generator to prioritise the type of views that serve your specific objective: Growth (broad reach), Engagement (comment activity), Sales (buyer-intent audience), or Authority (credibility signals in your niche).",
  },
  {
    q: "How do I create Reel ideas when I'm out of content ideas?",
    a: "The most reliable method for breaking content blocks is to use a structured prompt rather than waiting for inspiration. Instead of asking 'what should I post?', ask: 'What is the #1 mistake my audience makes that I could call out in 30 seconds?' or 'What question do I get asked most often that I could answer in a List format?' These constrained prompts force your brain to retrieve specific, filmable ideas rather than searching vaguely for 'content.' Other proven methods: (1) Use the Comments Mining technique — read the comments on your last 10 posts and look for unanswered questions or repeated frustrations. Each one is a Reel idea. (2) Run the generator with your niche set to Engagement goal to surface relatable and opinion content that speaks to your audience's existing conversations. (3) Batch generate 3–4 rounds of 12 ideas without filtering and build a content bank of 30–40 ideas to draw from over the next month.",
  },
  {
    q: "Is this Instagram Reel Idea Generator free to use?",
    a: "Yes — this Instagram Reel Idea Generator is completely free with no account required, no usage limits, and no premium tier. Enter your niche, audience, goal, experience level, and tone, and the AI generates 12 specific, filmable Reel ideas with hooks, formats, and filming tips in seconds. You can copy individual ideas or all ideas at once and regenerate as many times as needed for a fresh set. All 9 Reel format types, all 15 niches, all 4 goal modes, all 3 experience levels, and all 5 tone options are available on every generation at no cost.",
  },
];

const FAQ_SCHEMA = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: FAQ_ITEMS.map(item => ({
    "@type": "Question",
    name: item.q,
    acceptedAnswer: { "@type": "Answer", text: item.a },
  })),
};

// ─── Accordion ────────────────────────────────────────────────────────────────

function AccordionItem({ question, answer, index }: { question: string; answer: string; index: number }) {
  const [open, setOpen] = useState(false);
  const bodyRef = useRef<HTMLDivElement>(null);
  return (
    <div className={`rounded-2xl border bg-card shadow-sm overflow-hidden transition-all duration-200 ${open ? "border-primary/40 shadow-primary/10 shadow-md" : "border-border hover:border-muted-foreground/30"}`}>
      <button type="button" onClick={() => setOpen(v => !v)}
        className="w-full flex items-center justify-between px-6 py-5 text-left gap-4 group focus:outline-none focus-visible:ring-2 focus-visible:ring-primary/50 rounded-2xl"
        aria-expanded={open}>
        <span className="flex items-center gap-3">
          <span className={`flex-shrink-0 w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold transition-colors ${open ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"}`}>{index + 1}</span>
          <span className={`font-semibold text-base leading-snug transition-colors ${open ? "text-primary" : "text-foreground group-hover:text-primary"}`}>{question}</span>
        </span>
        <ChevronDown className={`w-5 h-5 flex-shrink-0 text-muted-foreground transition-transform duration-300 ${open ? "rotate-180 text-primary" : ""}`} />
      </button>
      <div ref={bodyRef} className="overflow-hidden transition-all duration-300 ease-in-out" style={{ maxHeight: open ? `${bodyRef.current?.scrollHeight ?? 600}px` : "0px" }}>
        <p className="px-6 pb-5 text-muted-foreground leading-relaxed text-sm">{answer}</p>
      </div>
    </div>
  );
}

// ─── Main component ───────────────────────────────────────────────────────────

export function InstagramReelIdeaGeneratorTool() {
  const [niche, setNiche] = useState("");
  const [audience, setAudience] = useState("");
  const [goal, setGoal] = useState("growth");
  const [tone, setTone] = useState("relatable");
  const [copied, setCopied] = useState<number | null>(null);
  const { outputs, loading, error, run } = useAiTool("instagram-reel-idea-generator");
  const { toast } = useToast();

  // Inject FAQ JSON-LD
  useEffect(() => {
    const id = "faq-schema-ig-reel-idea-gen";
    const s = document.createElement("script");
    s.type = "application/ld+json";
    s.id = id;
    s.textContent = JSON.stringify(FAQ_SCHEMA);
    document.head.appendChild(s);
    return () => { document.getElementById(id)?.remove(); };
  }, []);

  const handleGenerate = () => {
    if (!niche.trim()) {
      toast({ title: "Niche required", description: "Enter your Instagram niche.", variant: "destructive" });
      return;
    }
    run({ niche, audience, goal, tone, pillars: "education,entertainment,personal,tips" });
  };

  const copyItem = (text: string, i: number) => {
    navigator.clipboard.writeText(text);
    setCopied(i);
    setTimeout(() => setCopied(null), 2000);
  };

  return (
    <>
      {/* ── Tool Card ─────────────────────────────────────────── */}
      <Card className="p-6 space-y-4">
        <div className="flex items-center gap-2 mb-1">
          <Film className="text-purple-500" size={22} />
          <h2 className="font-semibold text-lg">Instagram Reel Idea Generator</h2>
          <span className="ml-auto flex items-center gap-1 text-xs font-semibold text-primary bg-primary/10 px-2.5 py-1 rounded-full border border-primary/20">
            <Sparkles size={11} /> AI Powered
          </span>
        </div>
        <div className="space-y-3">
          <div>
            <label className="text-sm font-medium mb-1 block">Your Niche *</label>
            <Input placeholder="e.g. fitness, cooking, fashion, travel, business..." value={niche} onChange={e => setNiche(e.target.value)} />
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <div>
              <label className="text-sm font-medium mb-1 block">Target Audience</label>
              <Input placeholder="e.g. beginners, moms..." value={audience} onChange={e => setAudience(e.target.value)} />
            </div>
            <div>
              <label className="text-sm font-medium mb-1 block">Goal</label>
              <select className="w-full border rounded-md px-3 py-2 text-sm bg-background" value={goal} onChange={e => setGoal(e.target.value)}>
                <option value="growth">Grow Followers</option>
                <option value="engagement">Boost Engagement</option>
                <option value="sales">Drive Sales</option>
                <option value="awareness">Brand Awareness</option>
                <option value="viral">Go Viral</option>
              </select>
            </div>
            <div>
              <label className="text-sm font-medium mb-1 block">Tone</label>
              <select className="w-full border rounded-md px-3 py-2 text-sm bg-background" value={tone} onChange={e => setTone(e.target.value)}>
                <option value="relatable">Relatable</option>
                <option value="educational">Educational</option>
                <option value="entertaining">Entertaining</option>
                <option value="inspirational">Inspirational</option>
                <option value="funny">Funny</option>
              </select>
            </div>
          </div>
        </div>
        <Button onClick={handleGenerate} disabled={loading} className="w-full bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600">
          {loading ? <><Loader2 className="animate-spin mr-2" size={16} />Generating with AI...</> : <><Sparkles size={16} className="mr-2" />Generate Reel Ideas</>}
        </Button>
        {error && <p className="text-sm text-red-500 mt-1">{error}</p>}
      </Card>

      {outputs.length > 0 && (
        <Card className="p-6 space-y-3">
          <div className="flex items-center justify-between">
            <h3 className="font-semibold">Reel Ideas</h3>
            <Button variant="outline" size="sm" onClick={() => { navigator.clipboard.writeText(outputs.join("\n")); toast({ title: "All ideas copied!" }); }}>
              Copy All
            </Button>
          </div>
          <div className="space-y-2">
            {outputs.map((idea, i) => (
              <div key={i} className="flex items-start gap-2 group p-3 rounded-lg border bg-muted/30 hover:bg-muted/60 transition-colors">
                <Film size={14} className="text-purple-500 mt-0.5 shrink-0" />
                <span className="flex-1 text-sm leading-relaxed">{idea}</span>
                <button onClick={() => copyItem(idea, i)} className="shrink-0 opacity-0 group-hover:opacity-100 transition-opacity text-muted-foreground hover:text-foreground">
                  {copied === i ? <Check size={15} className="text-green-500" /> : <Copy size={15} />}
                </button>
              </div>
            ))}
          </div>
        </Card>
      )}

      {/* ── How to Use ───────────────────────────────────────── */}
      <section className="mt-8">
        <div className="flex items-center gap-3 mb-6">
          <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center">
            <ListChecks className="w-5 h-5 text-primary" />
          </div>
          <h2 className="text-2xl font-bold font-display text-foreground">How to Use the Instagram Reel Idea Generator</h2>
        </div>
        <div className="grid sm:grid-cols-2 gap-4">
          {[
            {
              step: 1,
              title: "Select Your Niche, Audience & Content Pillars",
              desc: "Choose your content niche and optionally describe your specific target audience — the more specific, the more targeted the ideas. Select 2–6 content pillars from Education, Entertainment, Personal, Promotion, Inspiration, Tips, Behind-the-Scenes, and Motivation. Your pillar selection determines which categories of Reel ideas appear.",
            },
            {
              step: 2,
              title: "Set Your Goal, Experience Level & Tone",
              desc: "Goal adjusts which ideas are prioritised: Growth (broad reach hooks), Engagement (relatable content), Sales (buyer-intent ideas), Authority (deep educational content). Experience level adjusts format complexity. Tone modifies how each hook is phrased across all 12 ideas.",
            },
            {
              step: 3,
              title: "Get 12 Specific, Filmable Reel Ideas",
              desc: "12 ideas are generated with zero vague concepts — every idea includes the title, content angle, a scroll-stopping hook under 12 words, the format to film it in, the target audience segment, the post goal, and a specific filming tip. No two consecutive ideas share the same format.",
            },
            {
              step: 4,
              title: "Filter by Format for Batch Filming Efficiency",
              desc: "Use format filter tabs to view all Talking Head, Tutorial/Demo, or B-Roll ideas together. Batch filming — shooting all ideas of the same format in one session — is the most time-efficient way to create consistent Reel content. Copy any idea to clipboard for your content calendar.",
            },
          ].map(({ step, title, desc }) => (
            <div key={step} className="flex gap-4 p-5 rounded-2xl bg-muted/40 border border-border hover:border-primary/30 transition-colors">
              <div className="w-9 h-9 rounded-xl bg-primary text-primary-foreground font-bold text-sm flex items-center justify-center shrink-0">{step}</div>
              <div>
                <h3 className="font-bold text-foreground mb-1">{title}</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">{desc}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ── About ────────────────────────────────────────────── */}
      <section className="mt-2">
        <div className="flex items-center gap-3 mb-6">
          <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center">
            <Film className="w-5 h-5 text-primary" />
          </div>
          <h2 className="text-2xl font-bold font-display text-foreground">Instagram Reel Idea Generator — Creating Content That Actually Gets Views</h2>
        </div>
        <div className="space-y-8">
          <div>
            <h3 className="text-lg font-bold text-foreground mb-3 flex items-center gap-2">
              <Zap className="w-4 h-4 text-primary" /> Why Most Reel Ideas Fail Before They're Filmed
            </h3>
            <p className="text-muted-foreground leading-relaxed mb-3">
              The biggest Reel idea problem is not a lack of ideas — it's a lack of specific, filmable
              ideas. Most creators stare at a blank page and think 'I need to create a fitness Reel' or
              'I should post something about my business today.' These are categories, not ideas. A
              category cannot be filmed. An idea can. The difference between a creator who consistently
              posts strong content and one who posts inconsistently is not inspiration — it's a library
              of specific, structured ideas they can pull from at any time.
            </p>
            <p className="text-muted-foreground leading-relaxed mb-3">
              A filmable Reel idea answers four questions simultaneously: What exactly is the topic?
              What's the angle? What's the hook — the exact first sentence under 12 words? How do I
              film it — which specific format? Every idea this generator produces answers all four,
              plus includes a specific filming tip so you can move from reading to filming with no
              additional planning required.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              The format variety engine ensures your 12 ideas span multiple format types — Talking Head,
              B-Roll, POV/Skit, Before & After, Tutorial, Storytime, Myth-Busting, Mistake Callout, and
              List — because accounts that rotate formats attract different audience segments and avoid
              the algorithmic fatigue that comes from posting the same format type repeatedly. Pair your
              ideas with a strong{" "}
              <Link href="/tools/instagram-hook-generator" className="text-primary hover:underline font-medium">
                hook
              </Link>{" "}
              and a{" "}
              <Link href="/tools/instagram-caption-generator" className="text-primary hover:underline font-medium">
                purpose-built caption
              </Link>{" "}
              to complete every Reel's content strategy before you film a single frame.
            </p>
          </div>
          <div>
            <h3 className="text-lg font-bold text-foreground mb-3 flex items-center gap-2">
              <TrendingUp className="w-4 h-4 text-primary" /> Hooks, Batch Filming, and Building a Reel Library
            </h3>
            <p className="text-muted-foreground leading-relaxed mb-3">
              The hook is the most important 2 seconds of any Reel. Instagram's algorithm measures
              scroll-stop rate — what percentage of people who see your Reel in their feed stop and
              watch instead of scrolling. A weak hook means low scroll-stop rate, which means the
              algorithm stops distributing the Reel to new viewers no matter how good the content is
              after the first 3 seconds. A strong hook must create curiosity, tension, or surprise
              instantly. Every hook in this generator is under 12 words and tone-adjusted to your
              selected delivery style.
            </p>
            <p className="text-muted-foreground leading-relaxed mb-3">
              Batch filming is the production strategy that separates creators who post consistently
              from those who create in burst-and-drought cycles. The principle: group ideas by format,
              film all ideas of the same format in a single session, then edit in batches. A typical
              batch session of 4–5 Talking Head Reels takes 45–60 minutes total — setting up once,
              filming all, reviewing takes. This dramatically reduces the per-Reel time investment
              compared to setting up, filming, tearing down, and repeating for each individual video.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              Use the format filter tabs to group your 12 generated ideas by format, then plan your
              next filming session around one format type. Regenerate multiple rounds to build a content
              bank of 30–40 ideas before you film your first one — having a library removes the mental
              pressure of needing each individual Reel to succeed and gives you the volume needed for
              algorithmic consistency.
            </p>
          </div>
          <div>
            <h3 className="text-lg font-bold text-foreground mb-4 flex items-center gap-2">
              <Shield className="w-4 h-4 text-primary" /> What This AI Instagram Reel Idea Generator Includes
            </h3>
            <div className="grid sm:grid-cols-2 gap-3">
              {[
                "12 specific, filmable Reel ideas per generation — every idea includes title, content angle, hook, format, audience, goal, and how-to-film tip",
                "9 Reel format types — Talking Head, B-Roll + Text Overlay, POV/Skit, Before & After, Tutorial/Demo, Storytime, Myth-Busting, Mistake Callout, List/Tips",
                "Scroll-stopping hooks under 12 words for every idea — tone-adjusted for Bold, Relatable, Inspirational, Funny, or Controversial delivery",
                "15 niches — Fitness, Beauty, Business, Finance, Tech/AI, Education, Food, Travel, Lifestyle, Fashion, Relationships, Health, Coaching, Photography, and more",
                "4 goal modes — Growth (broad reach), Engagement (relatable), Sales (buyer-intent), Authority (deep educational ideas)",
                "3 experience levels — Beginner (Talking Head and List), Intermediate (mixed), Advanced (Storytime, multi-format, funnel-based ideas)",
                "5 tone options — Bold, Relatable, Inspirational, Funny, Controversial — each modifies how hooks are phrased across all 12 ideas",
                "Format filter tabs — view all Talking Head, Tutorial, POV, or other format ideas together for batch filming session planning",
                "Regenerate button — produces a fresh set of 12 ideas instantly without repeating ideas from the previous generation",
                "Copy to clipboard per idea — each idea copies as formatted plain text with all fields ready to paste into a content calendar or notes app",
              ].map((text, i) => (
                <div key={i} className="flex items-start gap-2.5 px-4 py-3 rounded-xl bg-muted/40 border border-border">
                  <Check className="w-4 h-4 text-primary mt-0.5 shrink-0" />
                  <span className="text-sm text-muted-foreground">{text}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ── Tips & Best Practices ────────────────────────────── */}
      <section className="mt-2">
        <div className="flex items-center gap-3 mb-6">
          <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center">
            <Lightbulb className="w-5 h-5 text-primary" />
          </div>
          <h2 className="text-2xl font-bold font-display text-foreground">Tips to Get the Most Out of Your Reel Ideas</h2>
        </div>
        <div className="grid sm:grid-cols-2 gap-3">
          {[
            "Generate 3–4 rounds before picking ideas — a content bank of 30–40 ideas gives you the volume for algorithmic consistency without the pressure of each Reel needing to succeed.",
            "Use the format filter tabs immediately — grouping ideas by format is the first step to planning a batch filming session that produces a week of content in under 2 hours.",
            "Film your Mistake Callout and Contrarian ideas first — these formats consistently generate the highest share rates and are the fastest path to new follower growth.",
            "Keep hooks under 12 words and film the first 2 seconds with maximum visual energy — scroll-stop rate in the first 2 seconds determines whether the algorithm distributes your Reel.",
            "Match your Experience Level honestly — beginners filming complex multi-cut formats produce lower quality content than polished Talking Head Reels, which consistently builds stronger audiences.",
            "Post your first 3 Reels from a batch within 7 days — consistent posting frequency signals to the algorithm that your account is active and worth distributing to new audiences.",
            "Combine the Sales goal with Authority tone — buyer-intent content delivered with authority signals builds the credibility needed for followers to convert into customers.",
          ].map((tip, i) => (
            <div key={i} className="flex items-start gap-2.5 px-4 py-3 rounded-xl bg-muted/40 border border-border">
              <Lightbulb className="w-4 h-4 text-primary mt-0.5 shrink-0" />
              <span className="text-sm text-muted-foreground">{tip}</span>
            </div>
          ))}
        </div>
      </section>

      {/* ── Related Instagram Tools ───────────────────────────── */}
      <section className="mt-2">
        <div className="flex items-center gap-3 mb-6">
          <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center">
            <ArrowUpRight className="w-5 h-5 text-primary" />
          </div>
          <h2 className="text-2xl font-bold font-display text-foreground">Related Instagram Tools</h2>
        </div>
        <div className="grid sm:grid-cols-2 gap-4">
          {[
            { name: "Instagram Hook Generator", path: "/tools/instagram-hook-generator", desc: "Craft the perfect opening line for your Reel — the hook is what determines whether viewers watch or scroll." },
            { name: "Instagram Caption Generator", path: "/tools/instagram-caption-generator", desc: "Write the caption that frames your Reel idea with a CTA that drives comments, shares, and saves." },
            { name: "Instagram Content Planner", path: "/tools/instagram-content-planner", desc: "Schedule your best Reel ideas into a strategic content calendar that builds audience momentum over time." },
            { name: "Instagram Hashtag Generator", path: "/tools/instagram-hashtag-generator", desc: "Find the targeted hashtags to amplify each Reel's organic reach to the widest relevant audience." },
          ].map(({ name, path, desc }) => (
            <a key={path} href={path} className="group flex items-start gap-4 p-4 rounded-2xl border border-border bg-muted/30 hover:bg-primary/5 hover:border-primary/30 transition-all duration-200">
              <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center shrink-0 group-hover:bg-primary/15 transition-colors">
                <ArrowUpRight className="w-4 h-4 text-primary" />
              </div>
              <div>
                <div className="font-semibold text-sm text-foreground group-hover:text-primary transition-colors">{name}</div>
                <div className="text-xs text-muted-foreground mt-0.5 leading-relaxed">{desc}</div>
              </div>
            </a>
          ))}
        </div>

        {/* CTA callout */}
        <div className="mt-4 p-5 rounded-2xl border border-primary/20 bg-primary/5">
          <p className="text-sm text-foreground font-semibold mb-1">Ready to take your Reel from idea to published?</p>
          <p className="text-sm text-muted-foreground">
            Start with the{" "}
            <Link href="/tools/instagram-hook-generator" className="text-primary hover:underline font-medium">
              Instagram Hook Generator
            </Link>{" "}
            to perfect your opening line, then use the{" "}
            <Link href="/tools/instagram-caption-generator" className="text-primary hover:underline font-medium">
              Instagram Caption Generator
            </Link>{" "}
            to write the caption that turns viewers into followers and saves.
          </p>
        </div>
      </section>

      {/* ── FAQ ──────────────────────────────────────────────── */}
      <section className="mt-2">
        <div className="flex items-center gap-3 mb-6">
          <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center">
            <ChevronDown className="w-5 h-5 text-primary" />
          </div>
          <h2 className="text-2xl font-bold font-display text-foreground">Frequently Asked Questions</h2>
        </div>
        <div className="space-y-3">
          {FAQ_ITEMS.map((item, i) => (
            <AccordionItem key={i} question={item.q} answer={item.a} index={i} />
          ))}
        </div>
      </section>
    </>
  );
}
